/* eslint-disable @typescript-eslint/no-unused-vars */
import { CircularProgress } from "@mui/material";
import AppContext from "@store/index";
// import AppContext from "@store/index";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Router from "next/router";
import React, { useContext, useEffect } from "react";

interface AppLayoutProps {
  title?: string;
  children?: React.ReactNode;
}

const AuthLayout: React.FC<AppLayoutProps> = ({ title, children }) => {
  const { data: session, status } = useSession();
  const { state, dispatch } = useContext(AppContext);

  useEffect(() => {
    if (status === "authenticated") {
      dispatch({
        type: "SET_AUTH",
      });
      return;
    }

    if (status === "unauthenticated") {
      Router.push("/auth/login");
    }
  }, [dispatch, session, status]);

  return (
    <>
      <Head>
        <title>Simba - Nueno {title ? `| ${title}` : ""} </title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"></meta>
        <meta name="description" content="Simba genesis" />
        <meta name="author" content="team-Eclipse.cmd" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {status === "authenticated" ? (
        <main className="min-h-screen">{children}</main>
      ) : (
        <div className="relative flex items-center justify-center min-w-full min-h-screen">
          <CircularProgress size={24} style={{ color: "#000000" }} />
        </div>
      )}
    </>
  );
};

export default AuthLayout;
