import Head from "next/head";
import React from "react";

interface PublicLayoutProps {
  title?: string;
  children?: React.ReactNode;
}

const PublicLayout: React.FC<PublicLayoutProps> = ({ title, children }) => {
  return (
    <>
      <Head>
        <title>Simba - Nueno {title ? `| ${title}` : ""} </title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"></meta>
        <meta name="description" content="Simba genesis" />
        <meta name="author" content="team-Eclipse.cmd" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main id="main-app" className="min-h-screen">
        {children}
      </main>
    </>
  );
};

export default PublicLayout;
